name: Run Python Script

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if there are any dependencies include them here

    - name: Run script
      run: |
        python ExtractFieldInformationFromObjects.py --input_dir ./scripts/python/ --output_dir ./results