name: Extract Metadata Fields Information From SObjects

on: 
  workflow_dispatch:

jobs:
  init:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if there are any dependencies include them here

    - name: Run script
      run: |
        python ./scripts/python/ExtractFieldInformationFromObjects.py --input_dir ./xml/objects --output_dir ./results

    - name: Commit and push if changed
      run: |
        git config user.name "Guilherme Monteiro"
        git config user.email "guivlm.sp@gmail.com"
        git pull origin HEAD:main
        git add -A
        git diff --quiet && git diff --staged --quiet || (echo 'No changes to commit' ; exit 0)
        echo 'Committing changes'
        git commit -m 'Update results'
        echo 'Pushing changes'
        git push origin HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GIT_HUB_ACTIONS }}
